# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'rack-test', '~> 1.1'
gem 'rspec', '~> 3.9'
gem 'sinatra', '~> 2.2'
